// Removes selectors the rendered site never uses from the ported WordPress CSS.
// Input: app/styles/src/*.css (full ports). Output: app/styles/*.css (purged). Corpus: every prerendered HTML page + component sources.
// Re-run after adding a block/component: `node scripts/purge-css.mjs` (needs a prior `next build` for the HTML corpus).
import { PurgeCSS } from 'purgecss'; import fs from 'node:fs'; import path from 'node:path';
const htmlDir = path.join(process.cwd(), '.next/server/app');
const content = [{ raw: '', extension: 'html' }];
(function walk(d) { if (!fs.existsSync(d)) return; for (const f of fs.readdirSync(d)) { const p = path.join(d, f); if (fs.statSync(p).isDirectory()) walk(p); else if (f.endsWith('.html')) content.push({ raw: fs.readFileSync(p, 'utf8'), extension: 'html' }); } })(htmlDir);
for (const dir of ['components', 'app', 'lib']) (function walk(d) { for (const f of fs.readdirSync(d)) { const p = path.join(d, f); if (fs.statSync(p).isDirectory()) walk(p); else if (/\.(tsx?|mjs)$/.test(f)) content.push({ raw: fs.readFileSync(p, 'utf8'), extension: 'tsx' }); } })(dir);
console.log('corpus: html pages', content.length);
// state classes toggled by JS/CSS at runtime, never present in the static HTML
const safelist = { standard: ['show', 'mega-toggle-on', 'mega-menu-open', 'mega-keyboard-navigation', 'is-active', 'current', 'dots', 'slick-prev', 'slick-next', 'slick-slide', 'slick-list', 'slick-track', 'slick-slider', 'slick-initialized', 'wpcf7', 'sent', 'sending', 'error', 'idle', 'cookie-banner', 'cookie-options', 'cookie-actions', 'regulatory-statement', 'skip-link', 'landing', 'landing-hero', 'rep-apr', 'risk-warning', 'post-hero'], deep: [/^mega-toggle/, /^mega-menu-open/, /^mega-sub-menu/, /^mega-indicator/, /^mega-menu-item/, /^mega-menu-link/, /^mega-menu-horizontal/, /^mega-menu-flyout/, /^mega-align/, /^mega-no-js/, /^max-mega-menu/, /^slick-(prev|next|slide|list|track|slider|initialized)/, /^wpcf7/, /^mce-/, /^mc_/, /^cookie-/, /^snap-/, /^lottie/, /^video-facade/, /^moneyhelper/, /^mas-/, /^embed-/, /^(green|lilac|yellow|purple|ltblue|cream|white|orange|navy|blue)$/, /^bg-/, /^has-/] };
// Attribute-based extractors: only class/id attribute values and tag names count as "used" (plain-word extraction kept everything because the prose contains words like "downloads").
const htmlExtractor = (c) => { const out = new Set(); for (const m of c.matchAll(/(?:class|className|id)=["'`]([^"'`]*)["'`]/g)) m[1].split(/\s+/).forEach((t) => t && out.add(t)); for (const m of c.matchAll(/<([a-z][a-z0-9-]*)/g)) out.add(m[1]); return [...out]; };
const tsxExtractor = (c) => { const out = new Set(); for (const m of c.matchAll(/(?:className|class|id)=\{?[`"']([^`"']*)[`"']/g)) m[1].replace(/\$\{[^}]*\}/g, ' ').split(/\s+/).forEach((t) => t && out.add(t)); for (const m of c.matchAll(/["'`]([a-z][a-z0-9-]*(?:\s+[a-z][a-z0-9-]*)*)["'`]/g)) m[1].split(/\s+/).forEach((t) => /^[a-z][a-z0-9-]*$/.test(t) && out.add(t)); for (const m of c.matchAll(/<([a-z][a-z0-9-]*)/g)) out.add(m[1]); return [...out]; };
const res = await new PurgeCSS().purge({ content, css: ['app/styles/src/theme.css', 'app/styles/src/megamenu.css'], safelist, variables: true, keyframes: true, fontFace: true, extractors: [{ extractor: htmlExtractor, extensions: ['html'] }, { extractor: tsxExtractor, extensions: ['tsx'] }] });
for (const r of res) { const out = path.join('app/styles', path.basename(r.file)); const before = fs.statSync(r.file).size; fs.writeFileSync(out, `/* PURGED build of ${path.relative(process.cwd(), r.file)} — edit the src file and run scripts/purge-css.mjs */\n` + r.css); console.log(path.basename(r.file), (before / 1024).toFixed(0), 'KB →', (r.css.length / 1024).toFixed(0), 'KB'); }
