// Prototype: WordPress rendered HTML -> MDX (frontmatter + section components). Verbatim text; layout via components.
import fs from 'fs'; import path from 'path'; import * as cheerio from 'cheerio'; import TurndownService from 'turndown'; import * as yaml from 'js-yaml';
import { ROOT, readJSON } from './lib.mjs';
const H = 'https://www.gmbcreditunion.com'; const inv = readJSON(ROOT + '/audit/raw/inventory.json');
const td = new TurndownService({ headingStyle: 'atx', bulletListMarker: '-', codeBlockStyle: 'fenced', emDelimiter: '*' });
td.keep(['u', 'sup', 'sub']);
td.addRule('script', { filter: ['script', 'noscript', 'style'], replacement: () => '' });
td.addRule('mas', { filter: n => n.nodeName === 'A' && /\bmas-widget\b/.test(n.getAttribute('class') || ''), replacement: (c, n) => `\n\n<MoneyHelperTool id="${n.getAttribute('id')}" href="${(n.getAttribute('href') || '').trim()}" lang="${n.getAttribute('lang') || 'en'}"${n.getAttribute('data-width') ? ` width="${n.getAttribute('data-width')}"` : ''}>${c}</MoneyHelperTool>\n\n` });
td.addRule('iframe', { filter: 'iframe', replacement: (c, n) => `\n\n<Embed src="${n.getAttribute('src')}"${n.getAttribute('title') ? ` title="${n.getAttribute('title').replace(/"/g, '&quot;')}"` : ''}${n.getAttribute('height') ? ` height={${parseInt(n.getAttribute('height')) || 600}}` : ''} />\n\n` });
td.addRule('br', { filter: 'br', replacement: () => '<br />' });
// inline text-align (editors centred many headings/paragraphs) → JSX element with a style prop; copy inside is unchanged
td.addRule('aligned', { filter: n => /^(H[1-6]|P|DIV)$/.test(n.nodeName) && /text-align:\s*(center|right)/.test(n.getAttribute('style') || '') && !/TypographyPresentation/.test(n.className || ''), replacement: (c, n) => { const tag = n.nodeName.toLowerCase(); const al = /right/.test(n.getAttribute('style')) ? 'right' : 'center'; const inner = c.trim().replace(/\n{2,}/g, '<br /><br />').replace(/\n/g, ' '); if (!inner) return ''; return `\n\n<${tag === 'div' ? 'div' : tag} style={{textAlign:"${al}"}}>${inner}</${tag === 'div' ? 'div' : tag}>\n\n`; } });
td.addRule('picture', { filter: 'picture', replacement: (c, n) => { const img = n.querySelector('img'); return img ? `![${img.getAttribute('alt') || ''}](${localMedia(img.getAttribute('src'))})` : ''; } });
td.addRule('img', { filter: 'img', replacement: (c, n) => `![${n.getAttribute('alt') || ''}](${localMedia(n.getAttribute('src'))})` });
td.addRule('junkdiv', { filter: n => n.nodeName === 'DIV' && /TypographyPresentation|RichText3/.test(n.className), replacement: c => c.trim() ? '\n\n' + c + '\n\n' : '' });   // Asana-pasted wrappers
td.addRule('a', { filter: n => n.nodeName === 'A' && n.getAttribute('href') && !/\bmas-widget\b/.test(n.getAttribute('class') || ''), replacement: (c, n) => { let h = n.getAttribute('href'); h = h.replace(/^https?:\/\/www\.gmbcreditunion\.com(?=\/|$)/, '') || '/'; if (/conesso_link_tag|utm_/.test(h) && /^\//.test(h)) { h = h.split('?')[0].replace(/^\/index\.php/, ''); if (!/\.[a-z0-9]+$/i.test(h) && !h.endsWith('/')) h += '/'; } if (/^\/media\//.test(h)) h = localMedia(h); const cls = (n.getAttribute('class') || '').trim(); const blank = n.getAttribute('target') === '_blank'; if (!cls && !blank) return `[${c}](${h})`; const btn = cls.match(/^button( button-alt)?$/); if (btn) return `<Button href="${h}"${btn[1] ? ' variant="secondary"' : ''}${blank ? ' target="_blank"' : ''}>${c}</Button>`; const keep = cls.replace(/\b(Hyperlink|SCXW\d+|BCX\d|sharedcomments-hyperlink)\b/g, '').trim(); return `<A href="${h}"${keep ? ` className="${keep}"` : ''}${blank ? ' target="_blank" rel="noopener"' : ''}>${c}</A>`; } });   /* theme buttons → <Button> (components/ui/button.tsx); Word-paste classes dropped */   /* <A> = the site link component (mapped in lib/mdx.tsx); literal <a> JSX would bypass it */
const PUB = ROOT + '/public';
/* static illustration matching a Lottie header animation (same artwork exported as SVG/PNG) */
const posterFor = l => { const base = l.replace(/-(LOTTIE\d*(-\d)?|Layers(-\d)?)\.(lottie|json)$/i, ''); for (const ext of ['.svg', '.png', '-1.svg', '2.svg']) if (fs.existsSync(PUB + base + ext)) return base + ext; return undefined; };
const stripVariant = p => { let cur = p; for (let i = 0; i < 4; i++) { const m = cur.match(/^(.*?)(-\d{2,4}x\d{2,4}|-scaled|-rotated|-e\d{13}|-\d+x\d+@2x)(\.[a-z0-9]+)$/i); if (!m) break; cur = m[1] + m[3]; if (fs.existsSync(PUB + cur)) return cur; } return cur; };
const localMedia = s => { let p = (s || '').replace(/^https?:\/\/www\.gmbcreditunion\.com/, ''); if (/^\/media\//.test(p) && !fs.existsSync(PUB + p.split('?')[0])) p = stripVariant(p.split('?')[0]); return p; };   /* size variants were not shipped; resolve to the original file */
const colourOf = cls => (cls || '').split(/\s+/).find(c => /^(yellow|lilac|purple|green|ltblue|orange|cream|white|navy|blue)$/.test(c)) || (cls || '').match(/bg-(\w+)/)?.[1] || undefined;
const md = html => td.turndown((html || '').replace(/<noscript>[\s\S]*?<\/noscript>/g, '')).trim();
const attrs = o => Object.entries(o).filter(([k, v]) => v !== undefined && v !== '' && v !== false).map(([k, v]) => typeof v === 'string' ? ` ${k}="${v.replace(/"/g, '&quot;')}"` : ` ${k}={${JSON.stringify(v)}}`).join('');
const alignOf = ($, el) => { const st = $(el).find('.data-header h2, h2').first().attr('style') || ''; return /center/.test(st) ? 'center' : /right/.test(st) ? 'right' : undefined; };
const inner = ($, el, sel) => { const e = sel ? $(el).find(sel).first() : $(el); return md(e.html()); };
const innerH3 = ($, el, sel) => inner($, el, sel).replace(/^#### /gm, '### ');   // card headings: h4 in WP markup, h3 for correct heading order (styled as h4)
function convertSection($, el) {
  const $s = $(el); const cls = $s.attr('class') || ''; const t = cls.split(/\s+/)[0];
  const colour = colourOf(cls) || colourOf($s.find('[class*="wrap-"],.panel,.data-content,.accordion').first().attr('class'));
  const hasTrust = $s.find('.trustpilot-widget').length > 0;
  const img = $s.find('.data-image img').first(); const lottie = $s.find('dotlottie-player').first();
  switch (t) {
    case 'header': case 'header-page': case 'header-title': {
      const buttons = $s.find('.wrap-buttons li').map((i, li) => ({ label: $(li).find('.data-label .text').text().trim() || $(li).text().trim(), href: localMedia($(li).find('a').attr('href')), icon: localMedia($(li).find('img').attr('src')) || undefined })).get();
      const label = $s.find('.data-content .label').first().text().trim() || undefined;
      return `<PageHeader${attrs({ variant: t === 'header' ? 'home' : t === 'header-title' ? 'title' : undefined, colour, label, trustpilot: hasTrust, image: img.length ? localMedia(img.attr('src')) : undefined, imageAlt: img.length ? (img.attr('alt') || '') : undefined, lottie: lottie.length ? localMedia(lottie.attr('src')) : undefined, poster: lottie.length ? posterFor(localMedia(lottie.attr('src'))) : undefined, buttons: buttons.length ? buttons : undefined })}>\n${md($s.find('.data-content').clone().find('.wrap-buttons, .label').remove().end().html())}\n</PageHeader>`; }
    case 'list-block': return `<ListBlock${attrs({ heading: md($s.find('.data-header h2').html()), align: alignOf($, el) })}>\n${$s.find('ul.list-listblock > li').map((i, li) => `<ListItem icon="${localMedia($(li).find('img').attr('src'))}">\n${inner($, li, '.column-content')}\n</ListItem>`).get().join('\n')}\n</ListBlock>`;
    case 'panel-section': return `<PanelSection>\n${$s.find('.row > .column > .panel').map((i, p) => `<Panel${attrs({ colour: colourOf($(p).attr('class')), title: $(p).find('.data-title').text().trim() })}>\n${inner($, p, '.data-content')}\n</Panel>`).get().join('\n')}\n${$s.find('footer.data-footer').length ? `<PanelFooter>\n${md($s.find('footer.data-footer').html())}\n</PanelFooter>` : ''}\n</PanelSection>`;
    case 'popout-block': return `<PopoutBlock${attrs({ colour, image: localMedia($s.find('.column-image img').attr('src')), imagePosition: $s.find('.row').children().first().hasClass('column-image') ? 'left' : undefined })}>\n${inner($, el, '.column-content .data-content')}\n</PopoutBlock>`;
    case 'video-section': return `<VideoSection${attrs({ video: $s.find('iframe').attr('src') })}>\n${inner($, el, '.column-content .data-content')}\n</VideoSection>`;
    case 'content-rows': return $s.find('.wrap-row').map((i, row) => { const $r = $(row); const heading = md($r.children('header.data-header').html()); const cols = $r.find('.row > .column').toArray().map(c => { const $c = $(c); if ($c.hasClass('column-img') || $c.hasClass('column-image')) return `<ColImage src="${localMedia($c.find('img').attr('src'))}" alt="${($c.find('img').attr('alt') || '').replace(/"/g, '&quot;')}" />`; const parts = $c.children().toArray().map(k => { const $k = $(k); if ($k.hasClass('wrap-icons')) return `<IconList>\n${$k.find('li').map((j, li) => `<IconListItem icon="${localMedia($(li).find('img').attr('src'))}">${md($(li).clone().find('img').remove().end().html())}</IconListItem>`).get().join('\n')}\n</IconList>`; return md($k.html()); }); return `<Col${attrs({ variant: $c.hasClass('column-icon') ? 'icon' : undefined })}>\n${parts.filter(Boolean).join('\n\n')}\n</Col>`; }); return `<ContentRow${attrs({ colour: colourOf($r.attr('class')), centred: $r.find('.row').hasClass('margin-auto') || undefined })}>\n${heading ? heading + '\n\n' : ''}${cols.join('\n')}\n</ContentRow>`; }).get().join('\n\n');
    case 'posts': return `<RelatedPosts${attrs({ count: $s.find('li').length })} />`;        // generated from content tree, not copy
    case 'posts-overview': return `<PostsOverview${attrs({ trustpilot: hasTrust })}>\n${md($s.find('.column-header').map((i, c) => $(c).html()).get().join('\n'))}\n</PostsOverview>`;
    case 'label-block': return `<StatBlock>\n${$s.find('.column').map((i, c) => `<Stat figure="${$(c).find('.data-figure').text().trim()}" label="${$(c).find('.data-label').text().trim()}" />`).get().join('\n')}\n</StatBlock>`;
    case 'icon-block': case 'block-icon-section': return `<IconGrid${attrs({ colour, heading: md($s.find('.data-header h2').html()), align: alignOf($, el), columns: ($s.find('ul').attr('class') || '').match(/split-(\d)/)?.[1] })}>\n${$s.find('ul > li').map((i, li) => `<IconItem icon="${localMedia($(li).find('img').attr('src'))}">\n${innerH3($, li, '.column-content')}\n</IconItem>`).get().join('\n')}\n</IconGrid>`;
    case 'colour-panels': return `<ColourPanels>\n${$s.find('li .panel').map((i, p) => `<ColourPanel${attrs({ colour: colourOf($(p).find('.data-content').attr('class')), image: localMedia($(p).find('img').attr('src')) })}>\n${inner($, p, '.data-content')}\n</ColourPanel>`).get().join('\n')}\n</ColourPanels>`;
    case 'box-slider': return `<BoxSlider${attrs({ heading: md($s.find('.data-header h2').html()), intro: md($s.find('.data-header p').html()), align: alignOf($, el) })}>\n${$s.find('.init-boxslider > div').map((i, b) => `<Box${attrs({ image: localMedia($(b).find('img').attr('src')) })}>\n${innerH3($, b, '.data-content')}\n</Box>`).get().join('\n')}\n</BoxSlider>`;
    case 'faq': return '<FAQSection>\n' + $s.find('.wrap-block').map((i, b) => `<FAQGroup${attrs({ heading: $(b).find('.data-header h2').text().trim(), colour: colourOf($(b).find('.accordion').attr('class')) })}>\n${$(b).find('.accordion > .wrap').map((j, w) => `<FAQ question="${$(w).find('a.toggle').first().text().replace(/\u00a0/g, ' ').trim().replace(/"/g, '&quot;')}">\n${md($(w).find('.inner').first().html())}\n</FAQ>`).get().join('\n')}\n</FAQGroup>`).get().join('\n\n') + '\n</FAQSection>';
    case 'info-block': return `<InfoBlock${attrs({ heading: md($s.find('.data-header h2').html()), align: alignOf($, el) })}>\n${md($s.find('.data-header').clone().find('h2').remove().end().html())}\n${$s.find('.panel').map((i, p) => `<InfoPanel${attrs({ year: $(p).find('.data-year').text().trim() || undefined })}>\n${md($(p).clone().find('.data-year').remove().end().html())}\n</InfoPanel>`).get().join('\n')}\n</InfoBlock>`;
    case 'contact-form': { const f = $s.find('form'); const prose = f.clone(); prose.find('input,select,textarea,label,button,fieldset,.wpcf7-form-control-wrap,.screen-reader-response,img').remove(); const introMd = md(prose.html()).replace(/(<br \/>\s*)+/g, '').trim(); return `<ContactForm${attrs({ formId: (f.attr('action') || '').match(/wpcf7-f(\d+)/)?.[1], fields: f.find('input,textarea,select').filter((i, x) => !/^_|^g-recaptcha/.test($(x).attr('name') || '') && $(x).attr('type') !== 'submit').map((i, x) => ({ name: $(x).attr('name'), type: x.tagName === 'input' ? $(x).attr('type') : x.tagName, required: $(x).attr('aria-required') === 'true' || !!$(x).attr('required') || undefined, label: $(x).closest('label').clone().find('span.wpcf7-form-control-wrap').remove().end().text().trim() || undefined })).get(), submit: f.find('input[type=submit]').attr('value') })}>${introMd ? '\n' + introMd + '\n' : ''}</ContactForm>`; }
    case 'postsingle': return md($s.find('article .data-content').html());
    default: return `{/* TODO unmapped section: ${cls} */}\n${md($s.html())}`;
  }
}
const catRows = fs.readFileSync(ROOT + '/audit/categorisation.csv', 'utf8').trim().split('\n').slice(1).map(l => l.match(/("([^"]|"")*"|[^,]*)(,|$)/g).map(c => c.replace(/,$/, '').replace(/^"|"$/g, '').replace(/""/g, '"')));
const catBy = Object.fromEntries(catRows.map(c => [c[0], { category: c[1], template: c[2], action: c[3], locked: c[4] === 'true', noindex_now: c[6] === 'true', content_path: c[7] }]));
const cards = readJSON(ROOT + '/audit/raw/post-cards.json', {}); const postTags = readJSON(ROOT + '/audit/raw/post-tags.json', {});
const FORCE_NOINDEX = /\/test\/$|thank-you-for-your-interest-agm-\d{4}\/$/;   // decision 3 (best practice)
function productFields($, url) {
  const text = $('section.panel-section, section.popout-block').text().replace(/\s+/g, ' ');
  const amt = text.match(/£([\d,]+)\s*[–-]\s*£([\d,]+)/); const apr = text.match(/([\d.]+)%\s*[–-]\s*([\d.]+)%\s*APR/i) || text.match(/([\d.]+)%\s*APR/i);
  const term = text.match(/(\d+)\s*months? max repayment term/i); const rep = text.match(/Interest:\s*([\d.]+)%\s*APR/i); const repAmt = text.match(/Loan Value:\s*£([\d,]+)/i); const repTerm = text.match(/Repayment Term:\s*(\d+) months/i); const repMonthly = text.match(/Monthly Repayment:\s*£([\d,.]+)/i); const repTotal = text.match(/Total amount:\s*£([\d,.]+)/i);
  const div = text.match(/dividend (?:return|rate)[^.]*?was\s*([\d.]+)%/i) || $('main').text().match(/dividend[^.]*?([\d.]+)%/i);
  const isLoan = /^\/loans\//.test(url.replace(H, ''));
  const o = { kind: isLoan ? 'loan' : 'savings' };
  if (amt) { o.amountMin = +amt[1].replace(/,/g, ''); o.amountMax = +amt[2].replace(/,/g, ''); }
  if (apr) { o.aprMin = +apr[1]; o.aprMax = +(apr[2] || apr[1]); } if (term) o.termMaxMonths = +term[1];
  if (rep) o.representative = { apr: +rep[1], amount: repAmt ? +repAmt[1].replace(/,/g, '') : undefined, termMonths: repTerm ? +repTerm[1] : undefined, monthly: repMonthly ? +repMonthly[1].replace(/,/g, '') : undefined, total: repTotal ? +repTotal[1].replace(/,/g, '') : undefined };
  if (!isLoan && div) o.dividendRate = +div[1];
  return o;
}
export function convert(url) {
  const r = inv[url]; const $ = cheerio.load(fs.readFileSync(path.join(ROOT, r.file), 'utf8')); const c = catBy[url] || {};
  const ld = []; $('script[type="application/ld+json"]').each((i, s) => { try { ld.push(JSON.parse($(s).html())); } catch { } });
  const fm = { title: r.title, description: r.meta_description || '', canonical: r.canonical, slug: url.replace(H, ''), category: c.category, template: c.template || r.template_guess, publishedAt: r.article_published || undefined, updatedAt: r.article_modified || undefined, ogImage: r.og_image ? r.og_image.replace(/^https?:\/\/www\.gmbcreditunion\.com/, '') : undefined /* exact original URL; size variants are rewritten to the original by proxy.ts */, ogDescription: r.og_description && r.og_description !== r.meta_description ? r.og_description : undefined, ogTitle: r.og_title && r.og_title !== r.title ? r.og_title : undefined, h1: r.h1 && r.h1 !== r.title.replace(/ \| .*$/, '') ? r.h1 : undefined, robots: r.robots_meta, locked: !!c.locked, noindex: /noindex/.test(r.robots_meta) || FORCE_NOINDEX.test(url), source_url: url, schema: ld[0] || undefined };
  if (c.template === 'product') fm.product = productFields($, url);
  if (r.template_guess === 'blog-post') { const hdr = $('section.header-page').first(); fm.featuredImage = localMedia(hdr.find('.data-image img').attr('src')); fm.headerColour = colourOf(hdr.attr('class')); fm.date = hdr.find('.data-date, .date, p').filter((i, e) => /^Date:/.test($(e).text().trim())).first().text().replace(/^Date:\s*/, '').replace(/\s+/g, ' ').trim() || undefined; fm.author = (ld[0]?.['@graph'] || []).find(n => n['@type'] === 'Person')?.name; const card = cards[url.replace(H, '')]; if (card) { fm.excerpt = card.excerpt; fm.cardTitle = card.cardTitle; fm.cardImage = localMedia(card.cardImage); fm.cardImageAlt = card.cardImageAlt; fm.featuredImageAlt = $('section.header-page .data-image img').attr('alt') || ''; } fm.tags = [...new Set([...$('a[rel="tag"]').map((i, a) => $(a).text().trim()).get(), ...(postTags[url.replace(H, '')] || [])])]; const cat = $('a[rel="category tag"], .data-category a').map((i, a) => $(a).text().trim()).get(); if (cat.length) fm.categories = cat; }
  const sections = $('main').children().toArray().filter(el => !(r.template_guess === 'blog-post' && /\bheader-page\b|\bposts\b/.test($(el).attr('class') || '')));
  $('a[href*="conesso_link_tag"]').each((i, a) => { let h = $(a).attr('href').replace(/^https?:\/\/www\.gmbcreditunion\.com/, ''); if (/^\//.test(h)) { h = h.split('?')[0].replace(/^\/index\.php/, ''); if (!/\.[a-z0-9]+$/i.test(h) && !h.endsWith('/')) h += '/'; $(a).attr('href', h); } });
  const body = sections.map(el => convertSection($, el)).join('\n\n');
  return `---\n${yaml.dump(JSON.parse(JSON.stringify(fm)), { lineWidth: 1000 })}---\n\n${body}\n`;
}
if (process.argv[2] === '--all') { let n = 0; for (const [url, c] of Object.entries(catBy)) { if (c.action !== 'build' || !c.content_path || c.content_path === '(generated)') continue; const out = convert(url); const f = path.join(ROOT, c.content_path); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, out); n++; } console.log('wrote', n, 'content files'); }
else if (process.argv[2]) { for (const u of process.argv.slice(2)) { const out = convert(H + u); const f = path.join(ROOT, 'audit/mdx-prototype', (u === '/' ? 'home' : u.replace(/^\/|\/$/g, '').replace(/\//g, '__')) + '.mdx'); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, out); console.log('wrote', path.relative(ROOT, f), out.length, 'chars'); } }
